### ISSUE TITLE
[Feature Request] Backup interval / Backup on Event

### ISSUE THREAD

**Issue by hamster65** [jneilliii/OctoPrint-BackupScheduler#1]
Hi  jneilliii,

thanks again for this plugin! Would it be possible to add a "backup on startup" function? Or a backup interval, like "every x days"?
Having fixed times does not work for me since my printer is powered up only when it needs to be..
Thanks!

**Comment by jneilliii** [comment]
So I must assume your pi is powered from your printer rather than powered separately? If that is the case, then you could achieve what you're asking for with the default OctoPrint system, without any plugin. To do a backup on startup you could use [events](https://docs.octoprint.org/en/master/events/index.html#server) in your config.yaml to run the CLI command for backups as documented [here](https://docs.octoprint.org/en/master/bundledplugins/backup.html#command-line-usage). So for example, to backup on startup you would add this to your config.yaml.

```
events:
    enabled: True
    subscriptions:
    -   event: Startup
        command: /home/pi/oprint/bin/octoprint plugins backup:backup
        type: system
```
